name: CI
on: [push, pull_request]
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - run: go mod download
      - run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - run: sqlc generate
      - run: go vet ./...
      - run: go test ./... -race -count=1
      - run: go build ./cmd/server
